import streamlit as st
from code.Generator import Generator
from code.config import Config
import torch

gen_hayao = Generator(in_channels=3)
config = Config()

if 'flag_hayo' not in st.session_state:
    st.session_state.flag_hayo = False

if 'input_photo' not in st.session_state:
    '''
    ##### 😖 Cannot find the image...

    ##### Did you upload???🤔🤔

    ##### If not please upload your image 😊😊
    '''
else:
    col1,col2 = st.columns(2,gap='large')
    with col1:
        with st.container(border=10):
            st.write('### Once have a look at the image you uploaded')
            st.image((st.session_state.input_photo*0.5+0.5).permute(1,2,0).numpy())
        
    with col2:
        with st.container(border=True):
            if st.session_state.flag_hayo:
                with st.status(label='loading state dict',expanded=True):
                    checkpoint = torch.load(config.CHECKPOINT_GEN_ANIMATION('Hayao'),map_location=config.DEVICE)
                    gen_hayao.load_state_dict(checkpoint)
                    'All Keys Matched'
                with st.status(label='generating image',expanded=True):
                    output = gen_hayao(st.session_state.input_photo)
                    st.write('##### This is the one generated by our model in Hayao Miyazaki\'s style 😎')
                    st.image((output*0.5+0.5).permute(1,2,0).detach().numpy(),clamp=True)
            else:
                st.write('click on the button below 👇 to generate')
    columns = st.columns(3)
    with columns[1]:
        st.session_state.flag_hayo = st.button(label="Generate in Hayao's Style")

            
    
