import streamlit as st
from code.Generator import Generator
from code.config import Config
import torch
import matplotlib.pyplot as plt
gen_shinkai = Generator(in_channels=3)
config = Config()


if 'input_photo' not in st.session_state:
    '''
    ##### 😖 Cannot find the image...

    ##### Did you upload???🤔🤔

    ##### If not please upload your image 😊😊
    '''
else:
    col1,col2 = st.columns(2,gap='large')
    with col1:
        with st.container(border=10):
            st.write('### Once have a look at the image you uploaded')
            st.image((st.session_state.input_photo*0.5+0.5).permute(1,2,0).numpy(),clamp=True)
        
    with col2:
        with st.container(border=True):
            if st.button(label="Generate in Shinkai's Style"):
                with st.status(label='loading state dict',expanded=True):
                    checkpoint = torch.load(config.CHECKPOINT_GEN_ANIMATION("Shinkai"),map_location=config.DEVICE)
                    gen_shinkai.load_state_dict(checkpoint)
                    'All Keys Matched'
                with st.status(label='generating image',expanded=True):
                    st.write('##### This is the one generated by our model in Makoto Shinkai\'s style 😎')
                    output = gen_shinkai(st.session_state.input_photo)
                    st.image((output*0.5+0.5).permute(1,2,0).detach().numpy(),clamp=True)
            
   

            

    
            
    
